name: CI/CD

on: [push]

jobs:
    server:
        runs-on: ubuntu-latest
        steps:
            - uses: action/checkout@v2
            - run: cd nissan && yarn build
    web:
        runs-on: ubuntu-latest
        steps:
            - uses: action/checkout@v2
            - run: cd dodge yarn build
