name: CI/CD

on: [push]

jobs:
    server:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - run: cd nissan && yarn && yarn build
    web:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - run: cd dodge && yarn && yarn build
