name: Pull code, and rebuild files

on:
    push:
        branches: [master]
jobs:
    update:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js
            - run: ls -a
