name: Pull code, and rebuild files

on:
    push:
        branches: [master]
jobs:
    update:
        runs-on: ubuntu-latest
        steps:
            - run: cd nissan && yarn build
            - run: cd dodge && yarn build
